apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicsafety

spec:
  replicas: 2

  selector:
    matchLabels:
      app: publicsafety

  template:
    metadata:
      labels:
        app: publicsafety

    spec:
      containers:
        - name: publicsafety
          image: 861142265676.dkr.ecr.us-east-2.amazonaws.com/publicsafety-ecr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2